server:
  port: 8086

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_service_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
